### ISSUE TITLE
node.js v0.10.29下child_process没有execSync方法

### ISSUE THREAD

**Issue by sleepwalkera** [raytaylorlin/hust-graduation-thesis-pandoc#1]
测试环境为kali linux 2.0

仓库里的nodejs为v0.10.29，没有execSync方法，有什么方法可以替代
其余功能均正常，一次通过

**Comment by raytaylorlin** [comment]
额。。。我的建议还是升级Node到最新版。。。
如果因为某些原因不能升级的话，可以尝试用第三方包来替代execSync方法，如[execSync](https://www.npmjs.com/package/execSync)、[sync-exec](https://www.npmjs.com/package/sync-exec)，或者另外再找其他的办法

**Comment by sleepwalkera** [comment]
sync-exec搞定

目前debian/kali stable下的nodejs都是v0.10.29这个版本

**Comment by raytaylorlin** [comment]
good
